version: '2.1'
services:
  db:
     image: mariadb:10.7.1
     environment:
       # assign a different root password for each environments.
       # Prevent to log my mistake on the wrong environment.
       MYSQL_ROOT_PASSWORD: test
       MAE_ENV: test
     ports:
     - 3317:3306
     volumes:
       # initialization
       - /home/max/devel/mae/envs/test:/docker-entrypoint-initdb.d
