name: Fames
version: '0.1.1'
license: MIT
dependencies:
- containers
- base >=4 && <5
- text >=0.11 && <2.0
- yesod >=1.4.1 && <1.5
- yesod-core >=1.4.17 && <1.5
- yesod-auth >=1.4.0 && <1.5
- yesod-static >=1.4.0.3 && <1.6
- yesod-form >=1.4.0 && <1.5
- yesod-persistent >=1.6.0 && <1.7
- yesod-fay >=0.7 && <0.9
- fay >=0.24.0.2 && <0.25
- fay-jquery >=0.6 && <0.7
- fay-text >=0.3 && <0.4
- cassava >=0.4.5 && <0.5
- classy-prelude >=0.10.2
- classy-prelude-conduit >=0.10.2
- classy-prelude-yesod >=0.10.2
- bytestring >=0.9 && <0.11
- persistent >=2.0 && <2.8
- persistent-mysql >=2.1.2 && <2.7
- mysql
- network >=3.1.1.1 && <3.2
- persistent-template >=2.0 && <2.6
- template-haskell
- shakespeare >=2.0 && <2.1
- hjsmin >=0.1 && <0.3
- monad-control >=0.3 && <1.1
- wai-extra >=3.0 && <3.1
- yaml >=0.8 && <0.9
- http-conduit >=2.1 && <2.3
- http-types >=0.12.3 && <0.13
- directory >=1.1 && <1.4
- warp >=3.0 && <3.3
- data-default
- aeson >=0.6 && <1.3
- aeson-qq
- conduit >=1.0 && <2.0
- conduit-extra
- streaming-commons
- monad-logger >=0.3 && <0.4
- fast-logger >=2.2 && <2.5
- wai-logger >=2.2 && <2.4
- file-embed
- safe
- unordered-containers
- vector
- time
- case-insensitive
- wai
- blaze-html
- blaze-markup
- split
- cryptohash
- formatting
- temporary
- these
- semialign
- these-lens
- Glob
- mtl >=2.2 && <2.3
- path-pieces >=0.2 && <0.3
- one-liner >= 1.0 && <2
- Metamorphosis >= 0.1.0.1
- fames-persist
- warehouse-planner >= 3.1.1
- microlens >= 0.4.1.1 && < 0.5
- microlens-th >= 0.4.1.1 && < 0.5
- curl >= 1.3.8 && < 1.4
- tagsoup >=  0.14.1 && < 0.15
- regex-tdfa >= 1.2.2 && < 1.3
- regex-base
- regex-compat-tdfa
- unliftio
- ghc-prim
- pointed >= 5
- yesod-media-simple >= 0.2.0.1 && < 0.2.1
- diagrams-lib >= 1.4.1.2 && < 1.5
- diagrams-cairo >= 1.4 && < 1.5
- diagrams-svg >= 1.4 && < 1.5
- parsec >= 3.1 && < 3.2
- colour >= 2.3.3 && < 2.4
- palette >= 0.3 && < 0.4
- Decimal >= 0.5.1 && < 0.6
- reducers >= 3.12 && < 3.13
- filepath >= 1.4.1.1  && < 1.5
- pretty-simple
- gitrev >= 0.1.3.1 && < 1.4
- mysql-simple
- comonad
- tagged
- iso3166-country-codes
- ghc
- mono-traversable
default-extensions:
- BlockArguments
- DeriveDataTypeable
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- NamedWildCards
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PatternSynonyms
- QuasiQuotes
- RankNTypes
- RecordWildCards
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- ViewPatterns
- MultiWayIf
- LambdaCase

library:
  source-dirs:
  - src
  - legacy
  - app
  - fay-shared
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Werror
      # - -Wincomplete-record-updates
      - -Wincomplete-patterns
      - -W
      - -Wno-partial-type-signatures
      - -Wno-type-defaults
      - -Wno-missing-local-signatures
      # - -fno-max-relevant-binds
      - -O0
      - -j6
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      # - -w
      - -W
      - -fwarn-tabs
      - -Wno-type-defaults
      - -Wno-partial-type-signatures
      - -O2
      - -j6

executables:
  Fames:
    main: main.hs
    source-dirs: app
    dependencies:
    - Fames
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -j6
    when:
    - condition: flag(library-only)
      buildable: false
    - condition: (flag(dev))
      then:
        ghc-options:
        - -O0
      else:
        ghc-options:
        - -O2
  FPlanner:
    main: Planner.hs
    source-dirs: tools
    other-modules: []
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - warehouse-planner
    - Fames
    when:
    - condition: flag(library-only)
      buildable: false
    - condition: (flag(dev))
      then:
        ghc-options:
        - -O0
      else:
        ghc-options:
        - -O2
  FAGenerator:
    main: FAGenerator.hs
    source-dirs: tools
    other-modules: []
    dependencies:
    - base
    - mysql-simple
    - split
    - filepath
    - directory
#k
#k  TextcartHelper:
#k    main: TextcartHelper.hs
#k    source-dirs: tools
#k    dependencies:
#k    - base
#k    - mysql-simple
#k    default-extensions: [ImplicitPrelude]

  # Import contact details from DPD local website to csv (using Selenium webdriver)
  DPDDump:
    main: DPDDump.hs
    source-dirs: tools
    other-modules:
    - DPDLib
    dependencies:
    - base
    - webdriver
    - text
    - cassava
    - bytestring
    - data-default-class
  # Import contact details from csv to fames database
  DPDImport:
    main: DPDImport.hs
    source-dirs: tools
    other-modules:
    - DPDLib
    dependencies:
    - Fames
    - base
    - webdriver
    - text
    - cassava
    - bytestring
    - data-default-class

  



tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -w
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - Fames
    - yesod-test >=1.5.0.1 && <1.6
    - yesod-core
    - yesod
    - yesod-auth
    - persistent
    - persistent-mysql
    - resourcet
    - monad-logger
    - shakespeare
    - transformers
    - hspec >=2.0.0
    - QuickCheck
    - classy-prelude
    - classy-prelude-yesod
    - aeson
    - cassava
    - yaml
    - temporary
    - http-types >=0.12.3 && <0.13
      #       # zghcid: # z so test is picked first
      #   zghicd:
      #     main: Spec.hs
      #     source-dirs:
      #     - test
      #     - legacy
      #     - fay-shared
      #     - src
      #     - app
      #     ghc-options:
      #     - -w
      #     - -threaded
      #     - -rtsopts
      #     - -with-rtsopts=-N
      #     dependencies:
      #     - base
      #     - yesod-test >=1.5.0.1 && <1.6
      #     - yesod-core
      #     - yesod
      #     - yesod-auth
      #     - persistent
      #     - persistent-mysql
      #     - resourcet
      #     - monad-logger
      #     - shakespeare
      #     - transformers
      #     - hspec >=2.0.0
      #     - QuickCheck
      #     - classy-prelude
      #     - classy-prelude-yesod
      #     - aeson
      #     - cassava
      #     - yaml
      #     - temporary
      #     - http-types >=0.9

flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
  brick:
    description: use brick for the warehouse plaanner
    manual: false
    default: true
