name: Fames
version: '0.0.0'
license: UnspecifiedLicense
dependencies:
- containers
- base >=4 && <5
- text >=0.11 && <2.0
- yesod >=1.4.1 && <1.5
- yesod-core >=1.4.17 && <1.5
- yesod-auth >=1.4.0 && <1.5
- yesod-static >=1.4.0.3 && <1.6
- yesod-form >=1.4.0 && <1.5
- yesod-fay >=0.7 && <0.9
- fay >=0.21.2.1 && <0.24
- fay-jquery >=0.6 && <0.7
- fay-text >=0.3 && <0.4
- cassava >=0.4.5 && <0.5
- classy-prelude >=0.10.2
- classy-prelude-conduit >=0.10.2
- classy-prelude-yesod >=0.10.2
- bytestring >=0.9 && <0.11
- persistent >=2.0 && <2.7
- persistent-mysql >=2.1.2 && <2.7
- mysql
- persistent-template >=2.0 && <2.6
- template-haskell
- shakespeare >=2.0 && <2.1
- hjsmin >=0.1 && <0.3
- monad-control >=0.3 && <1.1
- wai-extra >=3.0 && <3.1
- yaml >=0.8 && <0.9
- http-conduit >=2.1 && <2.3
- directory >=1.1 && <1.4
- warp >=3.0 && <3.3
- data-default
- aeson >=0.6 && <1.1
- conduit >=1.0 && <2.0
- conduit-extra
- streaming-commons
- monad-logger >=0.3 && <0.4
- fast-logger >=2.2 && <2.5
- wai-logger >=2.2 && <2.4
- file-embed
- safe
- unordered-containers
- vector
- time
- case-insensitive
- wai
- blaze-html
- split
- cryptohash
- formatting
- temporary
- these
- Glob
- mtl >=2.2 && <2.3
- path-pieces >=0.2 && <0.3
- generics-sop
- Metamorphosis >= 0.1.0.1
- microlens >= 0.4.8.0 && < 0.5
default-extensions:
- TemplateHaskell
- QuasiQuotes
- OverloadedStrings
- NoImplicitPrelude
- MultiParamTypeClasses
- TypeFamilies
- GADTs
- GeneralizedNewtypeDeriving
- FlexibleContexts
- FlexibleInstances
- EmptyDataDecls
- NoMonomorphismRestriction
- RankNTypes
- DeriveDataTypeable
- ViewPatterns
- TupleSections
- RecordWildCards
- PatternGuards
- PatternSynonyms
- StandaloneDeriving

library:
  source-dirs:
  - ./.
  - fay-shared
  - app
  exposed-modules:
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -w
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -w
      - -fwarn-tabs
      - -O2

executables:
  Fames:
    other-modules:
    main: main.hs
    source-dirs: app
    dependencies:
    - Fames
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
    - condition: flag(library-only)
      buildable: false

  FAGenerator:
    main: FAGenerator.hs
    source-dirs: tools
    dependencies:
    - base
    - mysql-simple
    - split
    - filepath
    - directory

  TextcartHelper:
    main: TextcartHelper.hs
    source-dirs: tools
    dependencies:
    - base
    - mysql-simple
    default-extensions: [ImplicitPrelude]


tests:
  test:
    main: Main.hs
    source-dirs: test
    ghc-options: -w
    dependencies:
    - base
    - Fames
    - yesod-test >=1.5.0.1 && <1.6
    - yesod-core
    - yesod
    - yesod-auth
    - persistent
    - persistent-mysql
    - resourcet
    - monad-logger
    - shakespeare
    - transformers
    - hspec >=2.0.0
    - hspec-stack-rerun
    - classy-prelude
    - classy-prelude-yesod
    - aeson
    - cassava
    - yaml
    - temporary
    - http-types >=0.9
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
