* TODO<2017-05-20 Sat> 
** TODO StockAdjustment
   - [ ] add modulo
   On generate adjusment modulo 6 (for example) optional
** TODO Collect MOP lost items
** TODO generate quickcheck
Allow stocktake without barcode.
similar to 0 takes but doesn't
For example if 24 of a styles are in stock
but only 5 are checked.
We don't want to invalidate the last stocktake (and not the box)
as it's indicate where (location and barcode) are the styles
if needs to be.
However, those items won't be taken into account when calculating 
stock adjustement if they have been already adjusted.

In fact, a stocktake can be seen as a queue for pending adjustement.
The real information where things are is in the boxtake table.
*** TODO change ZeroTake to QuickTake
- [ ] make sure that only zerotakes discard boxes
- [ ] make sure style, operator and date are carried over
* TODO <2017-03-04 Sat> 
** Edit packing list [7/9]
- [X] add message
 to tell the user the PL have been edited
- [X] use PL reference as first order ref
- [X] implement delete details
- [X] write tests for "edit details" features
- [X] refactor
  - [X] remove all view routes use parameter instead
    - [X] where to put PL types used by routes ?
- [X] display parsing error nicely
- [ ] use user textcart to fill form on error
- [ ] +Allow empty PL+
  - [ ] what to do with the document key ? (Can't be null)
   Doesn't work. Using the same document twice generate an error.
- [-] edit PL info (not details)
  - [ ] write tests
  - [X] implement
- [X] update document key table ?
  - [X] easy when replacing

* TODO <2017-01-08 Sun> 
- [X] refactor stocktake to validate and save on the same workflow
- [X] check stocktake dates in stockadj page
- [ ] filter stockadj by 
  - [ ] date
  - [ ] stocktake
- [X] add =complete style= button
- [ ] add stocktake date if needed
  but probably not as it's in the file.
- [X] check override erase everything
Doesn't, as it's not an update. It only overrides barcodes
Maybe it should.
- [  filter stocktake by
  - [ ] style
  - [ ] 
- [ ] link stock_id in stock adj to stocktake 
* PL
- [ ] TODO check groups are valid
- [-] deliver boxes
  - [X] mark them as deliver
  - [ ] generate automatic stocktake
    Boxtakess are generated. We could instead generate a stocktake sheet
to upload manually.
* Features
** TODO Stock Adjustment [0/1]
*** TODO Generate stock adjustment from stock take amendment [0/2]
- [ ] Generate the diff
between the stock adj saved in db and the one which 
should be generated from the actual stocktake.

The new adj should set the parent to the original

 - [ ] add *parent* field in stock_adjustement
 - [ ] find all descendant
When comparing expeced adj with one in DB , we need to not only 
check for the adj to amend but also to all it's descendant and possibly ascendant.
Basically, all adjustments related to the original one should be loaded and taken into consideration.


* Bugs
